FROM debian:12


RUN apt update && apt install -y nginx openssl && rm -rf /var/lib/apt/lists/*

COPY /ssl.sh /ssl.sh
RUN chmod +x /ssl.sh && /ssl.sh


COPY /nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -f /var/www/html/index.nginx-debian.html

CMD ["nginx", "-g", "daemon off;"]