FROM debian:12


RUN apt update && apt install -y \
php php-fpm php-mysql curl wget unzip mariadb-client \
&& rm -rf /var/lib/apt/lists/*


RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
&& chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp


COPY conf/www.conf /etc/php/8.2/fpm/pool.d/www.conf
COPY conf/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


WORKDIR /var/www/htlm

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm8.2", "-F"]